/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<number, number | string, number | string>;

export type PlantType = 'flower' | 'fruit' | 'vegetable';

export interface Garden {
  createdAt: Generated<string>;
  id: Generated<string>;
  locationDescription: string | null;
  name: string;
  targetHumidityLevel: Numeric | null;
  totalSurfaceArea: Numeric;
  updatedAt: Generated<string>;
  userId: string;
}

export interface Plant {
  createdAt: Generated<string>;
  gardenId: string;
  id: Generated<string>;
  idealHumidityLevel: number;
  name: string;
  plantationDate: string;
  plantType: PlantType;
  species: string;
  surfaceAreaRequired: Numeric;
  updatedAt: Generated<string>;
}

export interface PlantMetric {
  createdAt: Generated<string>;
  currentHumidityLevel: Generated<Numeric>;
  id: Generated<string>;
  lastIrrigationEndTime: string | null;
  lastIrrigationStartTime: string | null;
  plantId: string;
}

export interface User {
  age: number;
  createdAt: Generated<string>;
  email: string;
  firstName: string;
  id: Generated<string>;
  lastName: string;
  updatedAt: Generated<string>;
}

export interface DB {
  garden: Garden;
  plant: Plant;
  plant_metric: PlantMetric;
  user: User;
}
